module.exports = {

  inputs: {

  },


  exits: {
    success: {
      responseType: ``,
    },
    badRequest: {
      responseType: 'badRequest'
    },
    serverError: {
      responseType: 'serverError'
    },
  },


  fn: async function ({}, exits) {
    try {

      const coffeeMachine = this.req.id

      exits.success({url:"https://crm.dobryicoffee.ru/uploads/points/DC_HMI_null_Gamma_Stable_Release.apk"})
    } catch (err) {
      sails.log.error(err)
      throw {serverError: {message: err.message}}
    }
  }
};

/*
const work = {
  adContent: [{
    "destination": "making",
    "fileLength": 4080970,
    "fileName": "asd.mp4",
    "md5hash": "3d2115ae024fad97bf9db00b63053856"
  }, {
    "destination": "standby",
    "fileLength": 6191545,
    "fileName": "ogidanie.mp4",
    "md5hash": "588671fa8810e9f24c3c19bbe6ca5b21"
  }],
  companyId: "5d764ec1508e8f385ed751f0",
  controls: [],
  drinkSettings: {
    id: "64f9a2faef711e8bf649e440",
    currency: "RUB",
    name:"test",
    updatedAt: "2024-02-06T11:42:35.864Z",
    "drinks": [
      {
        "_id": "64f9a2faef711e8bf649e441",
        "external_id": "01",
        "formula": {
          "coffeeAmount": 100,
          "coffeeMilkTogether": true,
          "coffeeTemperature": 14,
          "concentration": 5,
          "drinkType": 5,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 5,
          "milkFoamTime": 25,
          "milkTime": 18,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_5",
        "index": 5,
        "location": 1,
        "lock": false,
        "price": 129.0,
        "special_price": 0.01,
        "task": 5,
        "title": "sdk_k95_drink_item_04",
        "title2": "300",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e442",
        "external_id": "02",
        "formula": {
          "coffeeAmount": 100,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 14,
          "concentration": 5,
          "drinkType": 6,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 6,
          "milkFoamTime": 25,
          "milkTime": 21,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_6",
        "index": 6,
        "location": 2,
        "lock": false,
        "price": 129.0,
        "special_price": 0.01,
        "task": 6,
        "title": "sdk_k95_drink_item_06",
        "title2": "300",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e443",
        "external_id": "03",
        "formula": {
          "coffeeAmount": 100,
          "coffeeMilkTogether": true,
          "coffeeTemperature": 14,
          "concentration": 5,
          "drinkType": 5,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 5,
          "milkFoamTime": 5,
          "milkTime": 23,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_4",
        "index": 5,
        "location": 3,
        "lock": false,
        "price": 129.0,
        "special_price": 0.01,
        "task": 5,
        "title": "sdk_k95_drink_item_105",
        "title2": "200",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e444",
        "external_id": "04",
        "formula": {
          "coffeeAmount": 285,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 14,
          "concentration": 5,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_131",
        "index": 1,
        "location": 4,
        "lock": false,
        "price": 109.0,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_02",
        "title2": "300",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e445",
        "external_id": "05",
        "formula": {
          "coffeeAmount": 60,
          "coffeeMilkTogether": true,
          "coffeeTemperature": 14,
          "concentration": 4,
          "drinkType": 5,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 5,
          "milkFoamTime": 27,
          "milkTime": 5,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_4",
        "index": 5,
        "location": 5,
        "lock": false,
        "price": 109.0,
        "special_price": 0.01,
        "task": 5,
        "title": "sdk_k95_drink_item_04",
        "title2": "200",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e446",
        "external_id": "06",
        "formula": {
          "coffeeAmount": 60,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 14,
          "concentration": 4,
          "drinkType": 6,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 6,
          "milkFoamTime": 25,
          "milkTime": 10,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_4",
        "index": 6,
        "location": 6,
        "lock": false,
        "price": 109.0,
        "special_price": 0.01,
        "task": 6,
        "title": "sdk_k95_drink_item_06",
        "title2": "200",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e447",
        "external_id": "07",
        "formula": {
          "coffeeAmount": 50,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 14,
          "concentration": 4,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_1",
        "index": 1,
        "location": 7,
        "lock": false,
        "price": 79.0,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_01",
        "title2": "50",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e448",
        "external_id": "08",
        "formula": {
          "coffeeAmount": 150,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 14,
          "concentration": 4,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_2",
        "index": 10,
        "location": 8,
        "lock": false,
        "price": 89.0,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_02",
        "title2": "150",
        "visible": true
      },
      {
        "_id": "64f9a2faef711e8bf649e449",
        "formula": {
          "coffeeAmount": 35,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 4,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 4,
          "milkFoamTime": 10,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_104",
        "index": 13,
        "location": 9,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 4,
        "title": "sdk_k95_drink_item_104",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44a",
        "formula": {
          "coffeeAmount": 120,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_131",
        "index": 12,
        "location": 10,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_131",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44b",
        "formula": {
          "coffeeAmount": 90,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_1",
        "index": 51,
        "location": 11,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_double_01",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44c",
        "formula": {
          "coffeeAmount": 120,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 4,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 4,
          "milkFoamTime": 28,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_4",
        "index": 55,
        "location": 12,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 4,
        "title": "sdk_k95_drink_item_double_04",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44d",
        "formula": {
          "coffeeAmount": 120,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 6,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 6,
          "milkFoamTime": 40,
          "milkTime": 10,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_6",
        "index": 57,
        "location": 13,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 6,
        "title": "sdk_k95_drink_item_double_06",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44e",
        "formula": {
          "coffeeAmount": 90,
          "coffeeMilkTogether": true,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 5,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 5,
          "milkFoamTime": 32,
          "milkTime": 12,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_5",
        "index": 56,
        "location": 14,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 5,
        "title": "sdk_k95_drink_item_double_05",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e44f",
        "formula": {
          "coffeeAmount": 120,
          "coffeeMilkTogether": true,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 5,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 5,
          "milkFoamTime": 8,
          "milkTime": 56,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_105",
        "index": 59,
        "location": 15,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 5,
        "title": "sdk_k95_drink_item_double_105",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e450",
        "formula": {
          "coffeeAmount": 200,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_101",
        "index": 52,
        "location": 16,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_double_101",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e451",
        "formula": {
          "coffeeAmount": 50,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_111",
        "index": 53,
        "location": 17,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_double_111",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e452",
        "formula": {
          "coffeeAmount": 70,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 4,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 4,
          "milkFoamTime": 20,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_104",
        "index": 58,
        "location": 18,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 4,
        "title": "sdk_k95_drink_item_double_104",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e453",
        "formula": {
          "coffeeAmount": 240,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_double_131",
        "index": 54,
        "location": 19,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_double_131",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e454",
        "formula": {
          "coffeeAmount": 0,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 0,
          "concentration": 0,
          "drinkType": 3,
          "hotwaterAmount": 100,
          "hotwaterTemperature": 1,
          "isMoreEspresso": false,
          "keyIndex": 3,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_3",
        "index": 3,
        "location": 20,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 3,
        "title": "sdk_k95_drink_item_03",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e455",
        "formula": {
          "coffeeAmount": 0,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 0,
          "concentration": 0,
          "drinkType": 7,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 7,
          "milkFoamTime": 0,
          "milkTime": 20,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_7",
        "index": 100,
        "location": 21,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 7,
        "title": "sdk_k95_drink_item_07",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e456",
        "formula": {
          "coffeeAmount": 0,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 0,
          "concentration": 0,
          "drinkType": 8,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 8,
          "milkFoamTime": 20,
          "milkTime": 0,
          "precook": false,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_8",
        "index": 101,
        "location": 22,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 8,
        "title": "sdk_k95_drink_item_08",
        "visible": false
      },
      {
        "_id": "64f9a2faef711e8bf649e457",
        "formula": {
          "coffeeAmount": 100,
          "coffeeMilkTogether": false,
          "coffeeTemperature": 2,
          "concentration": 1,
          "drinkType": 1,
          "hotwaterAmount": 0,
          "hotwaterTemperature": 0,
          "isMoreEspresso": false,
          "keyIndex": 1,
          "milkFoamTime": 0,
          "milkTime": 0,
          "precook": true,
          "repeatCoffee": 0,
          "repeatHotwater": 0
        },
        "image_name": "drink_121",
        "index": 11,
        "location": 23,
        "lock": false,
        "price": 0.01,
        "special_price": 0.01,
        "task": 1,
        "title": "sdk_k95_drink_item_121",
        "visible": false
      }
    ]
  },
  priceList: {"fiscal_provider": "atol", "payment_provider": "none"},
  softwareUpdate: [{
    "fileLength": 13616091,
    "fileName": "K95_HMI_388_Gamma_Stable_Release.apk",
    "md5hash": "e5e900bf6dfd7f944e39333a04c0c68e",
    "version": "K95_HMI_388"
  }, {
    "fileLength": 72468,
    "fileName": "K9X_CTR_APP_2.26UP.bin",
    "md5hash": "320829d7ffb2387f44188365ae39fc8d",
    "version": "K?95_CTR_226"
  }]
}
*/



