module.exports = {
  attributes: {
    basicVolume: {
      type: 'number',
      defaultsTo: 50
    },
    volume: {
      type: 'number',
      defaultsTo: 50
    },
    coffeeAmount: {
      type: 'number',
      defaultsTo: 0
    },
    coffeeMilkTogether: {
      type: 'boolean',
      defaultsTo: false
    },
    coffeeTemperature: {
      type: 'number',
      defaultsTo: 0
    },
    concentration: {
      type: 'number',
      defaultsTo: 0
    },
    drinkType: {
      type: 'number',
      isIn: [1, 2, 3, 4, 5, 6, 7, 8], //1-espresso 2-americano 3-hot_water 4-capuchino 5-macchiato 6-latte 7-hot_milk 8-cream
      defaultsTo: 1
    },
    hotwaterAmount: {
      type: 'number',
      defaultsTo: 0
    },
    hotwaterTemperature: {
      type: 'number',
      defaultsTo: 0
    },
    isMoreEspresso: {
      type: 'boolean',
      defaultsTo: false
    },
    keyIndex: {
      type: 'number',
      defaultsTo: 1
    },
    milkFoamTime: {
      type: 'number',
      defaultsTo: 0
    },
    milkTime: {
      type: 'number',
      defaultsTo: 0
    },
    precook: {
      type: 'boolean',
      defaultsTo: false
    },
    repeatCoffee: {
      type: 'number',
      defaultsTo: 0
    },
    repeatHotwater: {
      type: 'number',
      defaultsTo: 0
    },
    drink: {
      model: 'drink'
    },
    coffeeMachine: {
      model: 'drink'
    },
    sdk:{
      type:'string'
    },
    image:{
      type:'string'
    },
    formulaType:{
      type:'string',
      defaultsTo: 'custom',
      isIn: ['custom', 'default']
    },
    owner: false,
  },

  defaultFormulas() {
    return {
      capuchino_300: {
        basicVolume: 300,
        sdk: "sdk_k95_drink_item_04",
        image: "drink_4",
        keyIndex: 5,
        drinkType: 5,
        concentration: 4,
        coffeeAmount: 100,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 25,
        milkTime: 18,
        coffeeMilkTogether: true,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      latte_300: {
        basicVolume: 300,
        sdk:"sdk_k95_drink_item_06",
        image:"drink_6",
        keyIndex: 6,
        drinkType: 6,
        concentration: 4,
        coffeeAmount: 100,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 25,
        milkTime: 21,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      flat_white_200: {
        basicVolume: 200,
        sdk: "sdk_k95_drink_item_105",
        image: "drink_4",
        keyIndex: 5,
        drinkType: 5,
        concentration: 4,
        coffeeAmount: 100,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 5,
        milkTime: 23,
        coffeeMilkTogether: true,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      americano_300: {
        basicVolume: 300,
        sdk: "sdk_k95_drink_item_02",
        image: "drink_131",
        keyIndex: 1,
        drinkType: 1,
        concentration: 5,
        coffeeAmount: 285,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      cappuccino_200:{
        basicVolume: 200,
        sdk:"sdk_k95_drink_item_04",
        image:"drink_4",
        keyIndex: 5,
        drinkType: 5,
        concentration: 4,
        coffeeAmount: 60,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 27,
        milkTime: 5,
        coffeeMilkTogether: true,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      latte_200:{
        basicVolume: 200,
        sdk:"sdk_k95_drink_item_06",
        image:"drink_4",
        keyIndex: 6,
        drinkType: 6,
        concentration: 3,
        coffeeAmount: 60,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 25,
        milkTime: 10,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      espresso_50:{
        sdk: "sdk_k95_drink_item_01",
        image: "drink_1",
        keyIndex: 1,
        drinkType: 1,
        concentration: 5,
        coffeeAmount: 50,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      americano_150:{
        basicVolume: 150,
        sdk:"sdk_k95_drink_item_02",
        image:"drink_2",
        keyIndex: 1,
        drinkType: 1,
        concentration: 5,
        coffeeAmount: 150,
        coffeeTemperature: 14,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      macchiato:{
        sdk:"sdk_k95_drink_item_104",
        image:"drink_104",
        keyIndex: 4,
        drinkType: 4,
        concentration: 1,
        coffeeAmount: 35,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 10,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      coffee_with_cream: {
        image: "drink_131",
        sdk: "sdk_k95_drink_item_131",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 120,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      espresso_double: {
        image: "drink_double_1",
        sdk: "sdk_k95_drink_item_double_01",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 90,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      cappuccino_double: {
        image: "drink_double_4",
        sdk: "sdk_k95_drink_item_double_04",
        keyIndex: 4,
        drinkType: 4,
        concentration: 1,
        coffeeAmount: 120,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 28,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      latte_double: {
        image: "drink_double_6",
        sdk: "sdk_k95_drink_item_double_06",
        keyIndex: 6,
        drinkType: 6,
        concentration: 1,
        coffeeAmount: 120,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 40,
        milkTime: 10,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      latte_macchiato_double: {
        image: "drink_double_5",
        sdk: "sdk_k95_drink_item_double_05",
        keyIndex: 5,
        drinkType: 5,
        concentration: 1,
        coffeeAmount: 90,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 32,
        milkTime: 12,
        coffeeMilkTogether: true,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      flat_white_double: {
        image: "drink_double_105",
        sdk: "sdk_k95_drink_item_double_105",
        keyIndex: 5,
        drinkType: 5,
        concentration: 1,
        coffeeAmount: 120,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 8,
        milkTime: 56,
        coffeeMilkTogether: true,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      coffee_double: {
        image: "drink_double_101",
        sdk: "sdk_k95_drink_item_double_101",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 200,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      ristretto_double: {
        image: "drink_double_111",
        sdk: "sdk_k95_drink_item_double_111",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 50,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      macchiato_double: {
        image: "drink_double_104",
        sdk: "sdk_k95_drink_item_double_104",
        keyIndex: 4,
        drinkType: 4,
        concentration: 1,
        coffeeAmount: 70,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 20,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      coffee_with_cream_double: {
        image: "drink_double_131",
        sdk: "sdk_k95_drink_item_double_131",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 240,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      hotwater: {
        image: "drink_3",
        sdk: "sdk_k95_drink_item_03",
        keyIndex: 3,
        drinkType: 3,
        concentration: 0,
        coffeeAmount: 0,
        coffeeTemperature: 0,
        precook: true,
        hotwaterAmount: 100,
        hotwaterTemperature: 1,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      milk: {
        image: "drink_7",
        sdk: "sdk_k95_drink_item_07",
        keyIndex: 7,
        drinkType: 7,
        concentration: 0,
        coffeeAmount: 0,
        coffeeTemperature: 0,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 20,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      milk_foam: {
        image: "drink_8",
        sdk: "sdk_k95_drink_item_08",
        keyIndex: 8,
        drinkType: 8,
        concentration: 0,
        coffeeAmount: 0,
        coffeeTemperature: 0,
        precook: false,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 20,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      },
      coffee_pot: {
        image: "drink_121",
        sdk: "sdk_k95_drink_item_121",
        keyIndex: 1,
        drinkType: 1,
        concentration: 1,
        coffeeAmount: 100,
        coffeeTemperature: 2,
        precook: true,
        hotwaterAmount: 0,
        hotwaterTemperature: 0,
        milkFoamTime: 0,
        milkTime: 0,
        coffeeMilkTogether: false,
        isMoreEspresso: false,
        repeatCoffee: 0,
        repeatHotwater: 0
      }
    }
  }
}
